# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mark's Blog
tagline:          Why not
url:              http://mark.nadigs.net
paginate:         5
baseurl:          /
author:
  name:           Mark Nadig
  url:            https://twitter.com/marknadig
  email:          mark@nadigs.net

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/marknadig/marknadig.github.io
disqus_short_name: marknadig
